@echo off
setlocal EnableDelayedExpansion

REM =========================================================
REM Defina a aula aqui
REM =========================================================
set "AULA=07-aula07\07-2026-2026-04-07_MySQL-aula"

REM =========================================================
REM LISTA DE ALUNOS (adicione todos aqui)
REM =========================================================
set ALUNOS=F3620J8-ANDERSON_RAULINO_DA_SILVA H74HEB9-ANDERSON_XAVIER_DE_LIMA H603064-BARBARA_COSTA_NASCIMENTO R815544-BRUNA_MEDEIROS_DE_AGUIAR R8620H4-CAMILY_DE_SOUSA_OLIVEIRA_ROCHA F362EF1-CARLOS_EDUARDO_SILVA_SANTANA R434FI4-CAUA_HENRIQUE_R_DOS_SANTOS H6771G9-CAUAN_NUNES_LOPES G77AIA8-CLEYTON_ALVES_DA_COSTA R868GI1-DANILO_SALGADO_PERALTA_RIBEIRO F361DG6-DAVID_GABRIEL_SILVA_DE_JESUS H6094I1-DOUGLAS_VINICIUS_M_DOS_SANTOS R8459C7-EDER_RODRIGUES_DE_ALMEIDA R427FB0-FREDSON_SILVA_DOS_SANTOS H75GHA1-GABRIEL_GONCALVES_ZAGO R6607G5-GABRIEL_ROQUE_DOS_SANTOS H520495-GUILHERME_SOUSA_DOS_SANTOS R692AG0-GUSTAVO_RODRIGUES_O_MIGUEL R660IJ4-HECTOR_FABRO_PELLEGRINO N001AE7-JOAO_PEDRO_SILVA_CARVALHO H755HH9-JOAO_VITOR_FREITAS_DE_OLIVEIRA R8522D0-KAREN_DE_SOUSA_FARIA R659EI9-LEONARDO_ARAUJO_FREIRES H7501D3-LINCOLN_G_S_A_BARCELLOS G71CJI0-LORRANY_SILVA_AMORIM R5837H9-LUCAS_SOUZA_SANTANA R512ED7-MARIA_EDUARDA_RODRIGUES_ROMÃO H74FGI8-MATHEUS_BRIGANTI_DE_OLIVEIRA T160GF8-MAYSA_PONT_LOPES H671CE9-MIKAEL_MACEDO_DA_SILVA R849244-NICOLAS_TEIXEIRA_DE_AGUIAR G9960J0-SAMUEL_GONCALVES_SILVA R194655-THAISLA_LUIZA_SILVA_OLIVEIRA H768594-BRENO_BRITO_ALMEIDA R8662A7-BRUNO_ALVES_DE_SOUZA H759CH8-EDUARDO_DE_SOUSA_PEREIRA R861DH7-GUILHERME_VELOSO_DOS_SANTOS H75JAC6-HENRIQUE_ALEXANDRE_DAMACENO R8607D0-HENRIQUE_OLIVEIRA_GOMES R860922-ISAAC_LIMA_MARTINS R8708B6-LUISA_DOS_SANTOS_FIALHO R852IG6-MARIANE_CARNEIRO_SANTOS R839DA4-MATHEUS_DA_SILVA_BRITO R807053-MATHEUS_FERREIRA_PINHEIRO R6607C2-MICHEL_FARIAS_DA_SILVA R540EA6-MIGUEL_DOS_SANTOS_M_SIROMA R582639-NICOLAS_ZEMELLA_DE_MATOS R8699H4-PEDRO_EDUARDO_PAIVA_MEIRELES R852369-RAMON_BRIAN_G_DOS_SANTOS R850765-RAPHAEL_CAIQUE_DA_S_NEGREIROS H755565-RICHARD_RODRIGUES_MEDEIROS R8439J1-TAYNARA_NOGUEIRA_DOS_SANTOS H6882F0-THAMYRES_BANDEIRA_SANTOS R218BC1-THIAGO_FERREIRA_DIAS H66EIH4-VITOR_ALEXANDRE_DE_J_AMORIM R465993-VITOR_LUIZ_LUTA_FERNANDES R503IE5-VITORIA_DE_OLIVEIRA_VITOR R872696-YEDA_GOMES_DOS_SANTOS_CUSTODIO H57HED2-ANTONIO_FABIO_RIBEIRO_SAMPAIO H662893-BRUNA_SILVA_DOS_SANTOS H638879-GABRIEL_PIMENTA_DE_JESUS H64CJJ4-GABRIEL_REZENDE_DE_BARROS H624HJ8-GUILHERME_AUGUSTO_G_DE_MELO R693627-GUSTAVO_RODRIGUES_DE_BARROS H76FBE0-HENDREW_DOS_SANTOS_BRAZ R671IG1-HENRIQUE_BASTOS_LAET H471273-JERFFERSON_DE_SOUZA_NASCIMENTO R832384-JOAO_VICTOR_RODRIGUES_SILVA R6331J9-LUANA_GONÇALVES_BLASIO R865118-LUCAS_GABRIEL_MONTEIRO_SILVA H712742-LUIS_FERNANDO_ANDRADE_SANTOS H660467-LUIZA_NASCIMENTO_DA_CONCEICAO H675AE0-MANUEL_DOUGLAS_SILVA_ALVES R8506E5-MATHEUS_CAVALCANTE_DE_ALMEIDA R864CB0-MATHEUS_RENATO_B_ESTEVO G73IBG5-MATHEUS_SANTOS_RIBEIRO R8514D9-PEDRO_HENRIQUE_DE_P_MEDEIROS R826511-PEDRO_HENRIQUE_F_DE_SOUZA R802698-PEDRO_LIMA_DE_ALMEIDA_SOUZA H751616-RAMON_SANTOS_SILVA R830110-RHAUAN_SILVA_ARAUJO F3661B5-BRUNO_SILVA_DE_SOUZA R933EB6-CAIO_ALVES_DOS_SANTOS H78IIF9-DAVID_PEREIRA_MENDES H78IIB6-DIEGO_DUARTE_DE_ANDRADE H948746-ERICKLIS_VINICIUS_SOUZA_EVANGE H783216-GABRIEL_NONATO_EMERENCIANO T274427-GABRIEL_ROCHA_SANTOS R9580I0-GIOVANNI_LUCAS_FLORÊNCIA_VIANA H7635D7-IRAN_ALVES_DOS_SANTOS R9520A6-JESSICA_BORGES_OLIVEIRA R958825-JOAO_GABRIEL_DE_OLIVEIRA_FILIE T232341-JOAO_PEDRO_DE_OLIVEIRA H7891I8-JOAO_PEDRO_SALEM_MARQUES_SILVA T277973-JORDAN_SILVERIO_DE_SOUSA H77CBF4-JOSE_OZIEL_SILVA_DO_NASCIMENTO H779286-KAUE_FERREIRA_DA_SILVA R922DC5-LUAN_DE_JESUS_SILVA T307FD5-LUAN_OLIVEIRA_RUSSO H789GA6-LUCAS_NEUBAUER_LAPPAS_LINHARES H779669-PAULO_FELIX_DA_SILVA_ARAUJO R952DA5-PEDRO_HENRIQUE_MOREIRA_DA_SILV H790AC7-RAYANE_DOS_SANTOS_FALCAO F363IC2-THAINA_RODRIGUES_PAIVA H75FFF1-THIAGO_SANTOS_DO_CARMO F3650I9-VICTHOR_HUGO_S_A_DE_ALMEIDA R941JE0-VICTOR_FLOHR_FAGUNDES 

REM =========================================================
REM LOOP DOS ALUNOS
REM =========================================================
for %%A in (%ALUNOS%) do (

    echo Criando estrutura para %%A

    REM cria pasta do aluno
    mkdir "%AULA%\%%A" 2>nul

    REM cria exercicios 1..5
    mkdir "%AULA%\%%A\exercicio-1" 2>nul
    mkdir "%AULA%\%%A\exercicio-2" 2>nul
    mkdir "%AULA%\%%A\exercicio-3" 2>nul
    mkdir "%AULA%\%%A\exercicio-4" 2>nul
    mkdir "%AULA%\%%A\exercicio-5" 2>nul

    REM --------------------------
    REM Exercício 1
    REM --------------------------
    (echo #exercicio1)  > "%AULA%\%%A\exercicio-1\enunciado1.txt"
    (echo //exercicio1) > "%AULA%\%%A\exercicio-1\exercicio1.sql"

    REM --------------------------
    REM Exercício 2
    REM --------------------------
    (echo #exercicio2)  > "%AULA%\%%A\exercicio-2\enunciado2.txt"
    (echo //exercicio2) > "%AULA%\%%A\exercicio-2\exercicio2.sql"

    REM --------------------------
    REM Exercício 3
    REM --------------------------
    (echo #exercicio3)  > "%AULA%\%%A\exercicio-3\enunciado3.txt"
    (echo //exercicio3) > "%AULA%\%%A\exercicio-3\exercicio3.sql"

    REM --------------------------
    REM Exercício 4
    REM --------------------------
    (echo #exercicio4)  > "%AULA%\%%A\exercicio-4\enunciado4.txt"
    (echo //exercicio4) > "%AULA%\%%A\exercicio-4\exercicio4.sql"

    REM --------------------------
    REM Exercício 5
    REM --------------------------
    (echo #exercicio5)  > "%AULA%\%%A\exercicio-5\enunciado5.txt"
    (echo //exercicio5) > "%AULA%\%%A\exercicio-5\exercicio5.sql"

)

echo.
echo Estrutura criada com sucesso.
pause
